baseURL = "https://afrode-byte.github.io/"
title = ""
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"

[pagination]
pagerSize = 10

[params]
author = "Jailton De Macena Lima"
info = "Web Application Penetration Tester"
description = "Personal portfolio focused on Web Application Security, Offensive Security Research and practical penetration testing methodology."
keywords = "web application security, penetration testing, offensive security, owasp wstg, api security, burp suite"
colorScheme = "dark"
hideColorSchemeToggle = false

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github"
weight = 1
url = "https://github.com/afrode-byte/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/jailton-de-macena-lima/"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Methodology"
weight = 2
url = "methodology/"

[[menu.main]]
name = "Research"
weight = 3
url = "research/"

[[menu.main]]
name = "Projects"
weight = 4
url = "projects/"

[[menu.main]]
name = "Certifications"
weight = 5
url = "certifications/"

[[menu.main]]
name = "Contact"
weight = 6
url = "contact/"