baseURL = "https://afrode-byte.github.io/"
title = "Afrode"
theme = "hugo-coder"
locale = "en-US"
defaultContentLanguage = "en"

[pagination]
pagerSize = 10

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Jailton Lima"
info = "Web Application Penetration Tester"
description = "Portfolio focused on web application security, offensive security research and practical penetration testing methodology."
keywords = "web application security, penetration testing, offensive security, owasp wstg, api security, burp suite"
colorScheme = "dark"
hideColorSchemeToggle = false
customSCSS = ["scss/custom.scss"]

[params.footer]
hideCopyright = false
hideCredits = true

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github"
weight = 1
url = "https://github.com/afrode-byte/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/jailton-de-macena-lima/"

[[params.social]]
name = "Intigriti"
icon = "fa-solid fa-bug"
weight = 3
url = "https://app.intigriti.com/researcher/profile/jailton"

[[menu.main]]
name = "Home"
weight = 1
url = "/"

[[menu.main]]
name = "About"
weight = 2
url = "/about/"

[[menu.main]]
name = "Posts"
weight = 3
url = "/posts/"

[[menu.main]]
name = "Certifications"
weight = 4
url = "/certifications/"

[[menu.main]]
name = "Contact"
weight = 5
url = "/contact/"
